# As php-src's .github/scripts/setup-slapd.sh. @DIR@ and @SCHEMA@ are set at start.
include @SCHEMA@/core.schema
include @SCHEMA@/cosine.schema
include @SCHEMA@/inetorgperson.schema
include @SCHEMA@/nis.schema

pidfile @DIR@/slapd.pid
argsfile @DIR@/slapd.args

TLSCACertificateFile @DIR@/server.crt
TLSCertificateFile @DIR@/server.crt
TLSCertificateKeyFile @DIR@/server.key
TLSVerifyClient never
TLSProtocolMin 3.3

authz-regexp uid=usera,cn=digest-md5,cn=auth cn=usera,dc=my-domain,dc=com

database mdb
maxsize 104857600
suffix "dc=my-domain,dc=com"
rootdn "cn=Manager,dc=my-domain,dc=com"
rootpw secret
directory @DIR@/db

overlay sssvlv
sssvlv-max 10
sssvlv-maxkeys 5

overlay ppolicy

overlay dds

index objectClass eq
index entryExpireTimestamp eq
